### ISSUE TITLE
Horizontally-split windows

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-suggestions#10]

**Comment by sschlein** [comment]
It hasn't become a priority for 3 months and improvements like line-wrapping and the upcoming table view feature to lower the priority even more. I'm closing this issue for not but believe that we will implement this at some point when Tinkerwell keeps growing.

**Comment by pryley** [comment]
In my case, horizontal view would be useful as I use Tinkerwell in Sidecar.
