### ISSUE TITLE
Auto Installation Not Working

### ISSUE THREAD

**Issue by vmitchell85** [beyondcode/tinkerwell-suggestions#100]
I keep getting notified that there is a new version that will auto install on exit but no matter how many times I exit and reopen it doesn't seem to install

![image](https://user-images.githubusercontent.com/1248035/74546787-1f87ed80-4f19-11ea-8a30-f73d48a9ff3c.png)

**Comment by sschlein** [comment]
We are looking into this already but don't have a solution yet. You can get the newest version on the website to get rid of this message:

https://tinkerwell.app/management
