### ISSUE TITLE
Ability to dynamically set/push environment variables or prepend code

### ISSUE THREAD

**Issue by jeffkarney** [beyondcode/tinkerwell-suggestions#102]
One thing that seems to be missing is the ability to push or set dynamic variables before the driver runs the application bootstrap code.

Imagine applications that can connect to different databases based on an environment variable or maybe a multi-tenant application that uses the domain name to select a database.

In the most simplest form, the ability to prepend some custom code that is loaded before bootstrapping. There could be another button on the side of the app that switches to a new code pane. Any code here would load before the bootstrapping. So you could set all your desired environment variables, then go back to the normal code pane and continue tinkering.

**Comment by mpociot** [comment]
@jeffkarney The easiest way to do this is right now is by creating a custom, project specific, driver that bootstraps the application the way you need it: https://github.com/tinkerwellapp/drivers

There you have complete freedom over how the apps/frameworks should be bootstrapped before the Tinkerwell code gets evaluated.

**Comment by jeffkarney** [comment]
@mpociot I Think you are misunderstanding what I am trying to suggest.

I understand the driver can do things before the actual Tinkerwell code is evaluated. However that must all be hard coded or already exist. There is currently no way (that I know of) to dynamically change things from Tinkerwell before the bootstrapping happens.

Imagine I have a single code base that can be accessed from multiple domain names. A multi-tenant site. In the driver bootstrap method I include the bootstrap file for my application. This file uses the domain name to determine which database to connect to. The code in this file is ran before the code I have in Tinkerwell.

As you suggest, I could add something here...

```
public function bootstrap($projectPath)
{
        $domain_name = 'www.domain01.com'; // this is hard coded here or in some other file, not able to be changed from within Tinkerwell
        require $projectPath . '/bootstrap.php';
}
```

However now if I want to run code where $domain_name is something other than 'www.domain01.com' I have to either change the code int the driver or change some other file on the server.

Now imagine something along the lines of...

```
public function bootstrap($projectPath, $vars = [])
{
        $domain_name = $vars['domain_name'];  // $vars['domain_name'] comes from a setting in the Tinkerwell application
        require $projectPath . '/bootstrap.php';
}
```

Where $vars gets passed in from something in the Tinkerwell application. The user could set/change the values from the Tinkerwell application that get passed in here. These are able to then be used to perform any setup or configuration needed before the actual bootstrapping takes place.

Maybe this can happen somewhere in the custom context menus. Or the driver could have the ability to make certain setting fields available to the user. They could be free entry fields or created from options.

The point is that they can be changed from the actual Tinkerwell application.
