### ISSUE TITLE
Lumen Driver not working for me

### ISSUE THREAD

**Issue by xitox97** [beyondcode/tinkerwell-suggestions#104]
Hello guys, Im still new using Tinkerwell. It works well in Laravel App, but in Lumen its a bit weird.

For example: If I tried to used Eloquent to get first data in modal. I did not get the data instead I only get the properties of the modal
![Image of Yaktocat](https://camo.githubusercontent.com/79761e8f53d2b7886702dfb4dbee7c606470da62/68747470733a2f2f692e696d6775722e636f6d2f53395470364b682e706e67)

For second problem is, In Laravel app, If I tried to open query inspection(Ctrl + Shift + R) I got this error
![Image of Yaktocat](https://i.imgur.com/vyaqNSN.png)

Im using on Windows.

**Comment by xitox97** [comment]
Second problem is solved by upgrading php version. But first problem still not solved, anyone have any ideas?

**Comment by mpociot** [comment]
This is a known issue with the Lumen driver, that will be fixed in the next release.
Please try and use this custom driver in the meantime:

Create a folder called `.tinkerwell` in your project directory.
Place this file in there called `CustomLumenTinkerwellDriver.php`

https://gist.github.com/mpociot/d0b2d17d9e74128a6341b79c4c0c481e

**Comment by xitox97** [comment]
Already tried the new  `CustomLumenTinkerwellDriver.php`, still same. I need to add ->toArray() to be able to see the data. Anyways goods to know that it will be fixed in next release.

**Comment by georanma** [comment]
Just fyi, I had to use @mpociot's driver snippet to this my Lumen app to be recognized with Lumen 7.0.2, Homestead 9.3.0, and Tinkerwell 2.6.0.

**Comment by gundamew** [comment]
Lumen 5.8.12 and Tinkerwell 2.7.0. Try to test database factories but encountered errors below:

```
In LaravelTinkerwellDriver.php line 24:
                                                            
  Call to undefined method App\Console\Kernel::bootstrap()
```

Solved by `CustomLumenTinkerwellDriver.php`.
