### ISSUE TITLE
Add Laravel cheatsheet to desktop app

### ISSUE THREAD

**Issue by fadbad** [beyondcode/tinkerwell-suggestions#109]
Integrating the same feature (Laravel Cheatsheet) found in WEB app into DESKTOP app will be a great time saver. Thank you, please advise

**Comment by sschlein** [comment]
We appreciate your idea, but Tinkerwell is highly opinionated and also supports other frameworks. We don't think this fits the scope of the desktop app and recommend using the web version for these Laravel features.
