### ISSUE TITLE
Tinkerwell cant connect to database

### ISSUE THREAD

**Issue by ronssij** [beyondcode/tinkerwell-suggestions#110]
![image](https://user-images.githubusercontent.com/24932380/75129301-5ae99f80-5703-11ea-8f18-fcf42b111e89.png)
![image](https://user-images.githubusercontent.com/24932380/75129345-879db700-5703-11ea-888b-926800761101.png)

I don't know what is causing this not to work.

**Comment by ronssij** [comment]
I found out that this is an issue with my MySQL version 8.
Fixed this issue with this MySQL command,
> ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';

**Comment by Prashank25** [comment]
For what it's worth, in my case this error showed up because I had mysql 8 host set to `localhost` in .env. Changing it to `127.0.0.1` fixed it.

**Comment by ronssij** [comment]
@Prashank25 Never tried that though. If that works for you, Awesome!! :D
