### ISSUE TITLE
set custom default project (working directory path) 

### ISSUE THREAD

**Issue by joisarjignesh** [beyondcode/tinkerwell-suggestions#112]
every time i open tinkerwell then i set working directory path always so give a new option(feature) to set default project(working directory project). 
i am using ubuntu 18.04 ..(not working on this os)

**Comment by sschlein** [comment]
Thank you for your suggestion! Tinkerwell is opinionated and we don't think this is a use case for most people. We provide a recent projects option in the latest version to select a project quickly and hope this comes close enough to your request :)

**Comment by joisarjignesh** [comment]
@sschlein  i got it on latest version recent projects thanks

**Comment by squatto** [comment]
I've been working *very* heavily in Tinkerwell over the past two weeks and I can assure you, it is **painfully** annoying having to set the project directory on every single new tab. Pressing ⌘+T for a new tab and then having to use my mouse and go to File > Open Recent _every time_ just plain sucks.

I've found that the majority of the time I'm able to press ⌘+O and I'm already at the project's root. However, if you save your script to a different folder, open a script, or do _anything_ that involves a file dialog, ⌘+O will open to whatever your last folder was. Then you have to go find your project folder _again_.

You could easily keep Tinkerwell's opinionated nature present with a setting like this:

```
Default when opening a new tab:

(o) Use the default Laravel app
( ) Use the following directory:
     [folder input field] <Browse>
```

For those of us that work on a single PHP project for work, this makes perfect sense. You rarely would want anything *but* your project as the default directory. Even if you work in multiple different PHP projects, odds are that when you open a new tab, you are going to be working in the same project as the tab you just left.
