### ISSUE TITLE
Copying output from result panel

### ISSUE THREAD

**Issue by wrabit** [beyondcode/tinkerwell-suggestions#113]
I can't seem to highlight and copy output text from the right side result panel.

**Comment by sschlein** [comment]
Which version and OS are you using? I just tested with 2.4 and macOS and it works :)

**Comment by wrabit** [comment]
Ah ok, it's errors / exceptions that I cannot select and copy. Would be useful if it was able top select any text.

**Comment by sschlein** [comment]
Fixed with 2.6.0 :)
