### ISSUE TITLE
Cannot open my own laravel project named "project.app"

### ISSUE THREAD

**Issue by antergos98** [beyondcode/tinkerwell-suggestions#116]
I have a laravel project in a folder called "project.app" and I can't open it in tinkerwell because of the .app. Is there any way to fix this? I can always rename the project folder but I'd like to keep the .app.

**Comment by sschlein** [comment]
We ended up renaming our folders, for example for tinkerwell.app 😂

There is no way to handle that as long as you don't want to recreate the whole finder select-directory view (like phpstorm did). The only way to get around is might be this feature: https://github.com/beyondcode/tinkerwell-suggestions/issues/45
