### ISSUE TITLE
SSH not working

### ISSUE THREAD

**Issue by decadence** [beyondcode/tinkerwell-suggestions#118]
Can't work with SSH.

Output is - Could not open input file: /tmp/tinker_compressed.phar. Do you have any ideas what's going on?

SSH user can enter in /tmp folder and create files there.

Tinkerwell Windows 2.2.1

**Comment by decadence** [comment]
Investigation with admins shows that Tinkerwell uploaded file in directory: /var/www/tmp/tinker_compressed.phar not in /tmp. Home folder is /var/www. Maybe Tinkerwell considers it as root folder? (/)

**Comment by decadence** [comment]
Figured it out: MySecureShell was the problem.

**Comment by albalooshi** [comment]
@decadence what was the solution?

**Comment by decadence** [comment]
Disable MySecureShell or check write permissions to /tmp folder for your user.

**Comment by albalooshi** [comment]
I did not have MySecureShell installed and the write permission of /tmp was fine.

For me the solution was to delete the tinker files on the server:
```
cd /tmp/
rm tinker_compressed.phar tinker.txt tinker.php
```
