### ISSUE TITLE
Default view name in HTTP mode

### ISSUE THREAD

**Issue by decadence** [beyondcode/tinkerwell-suggestions#119]
I select "Tinker - HTTP" and change default view name during testing.
Can someone say default view name so Tinkerwell can use HTML from top panel?

![image](https://user-images.githubusercontent.com/1434668/75456068-1ff99d00-598b-11ea-9a37-9a8da8516951.png)

Reinstall didn't work (settings are saved somewhere).

Tinkerwell Windows 2.2.1

**Comment by decadence** [comment]
`__tinker__::tinker`

**Comment by timvdalen** [comment]
It would really help if this was documented in the FAQ! (Or a button in the interface)
