### ISSUE TITLE
Save/load Tinkerwell snippets

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-suggestions#12]

**Comment by PascalHesselink** [comment]
If this future request is approved, will there be an option to save snippets per project instead of globally?

**Comment by mpociot** [comment]
@PascalHesselink One possible solution that is floating around is the idea to create a `.tinkerwell` file within the open project that holds all snippets. This way they would be per project (and could be put into version control)
But it's at the moment just one of the possible solutions for this :)

**Comment by PascalHesselink** [comment]
> @PascalHesselink One possible solution that is floating around is the idea to create a `.tinkerwell` file within the open project that holds all snippets. This way they would be per project (and could be put into version control)
> But it's at the moment just one of the possible solutions for this :)

Would be great, I was thinking about the exact same thing.
We'll see in the future if this will be applied or not.

**Comment by jamie-brown** [comment]
I was just coming to request this feature. I would love to see this in Tinkerwell. 

I was thinking of the ability to save snippets that we could then list and maybe have buttons on each snippet to 'Run' or 'Edit'.

**Comment by sschlein** [comment]
Solved with the drivers feature: https://github.com/tinkerwellapp/drivers
