### ISSUE TITLE
Can't delete SSH session on Windows

### ISSUE THREAD

**Issue by decadence** [beyondcode/tinkerwell-suggestions#121]
As title says: you can't delete existing SSH session on Windows version.

Update: you can delete it with Delete key but more intuitive would be adding menu item to this context menu.

![2020-02-27_19-57-05](https://user-images.githubusercontent.com/1434668/75466640-8c7c9800-599b-11ea-8bb6-2dd0e5c2bd17.png)

**Comment by sschlein** [comment]
Thank you for your suggestion but we want to have a minimal UI and think that deleting with the delete key is sufficient for our audience.

**Comment by decadence** [comment]
As you wish but I think in this case UI is too minimal :)

For example comment from [Reedit](https://www.reddit.com/r/laravel/comments/esviv0/tinkerwell_20_is_released_with_windows_and_linux/
):
"And deleting connections is impossible, aside from overwriting them with new info".

Users just don't recall Delete button in the majority of cases.
