### ISSUE TITLE
SSH Connection for IDE Integration

### ISSUE THREAD

**Issue by SaundersB** [beyondcode/tinkerwell-suggestions#124]
I'd love to be able to run my IDE scratch file (PHPStorm) with my SSH connection in Tinkerwell.

**Comment by sschlein** [comment]
https://github.com/beyondcode/tinkerwell-suggestions/issues/60 👀

(Details in one of the next releases)

**Comment by simensen** [comment]
Hello! I took a look at #60 but I don't see how it relates to this. I, too, am wanting to do Tinkerwell with an IDE (PhpStorm) via SSH and not sure how to get it to work correctly. This issue looked like the closest thing to what I'm asking about.
