### ISSUE TITLE
Save and share web link from desktop app

### ISSUE THREAD

**Issue by jesseleite** [beyondcode/tinkerwell-suggestions#125]
It would be cool if we could save and share a tinkerwell web link from the desktop app.  This button could copy the tinkerwell input into a new [web.tinkerwell.app](https://web.tinkerwell.app/) instance and automatically copy the shareable link to the clipboard for pasting.

This feature would obviously have to be disabled if working on a custom app instance, but could be super useful for sharing generic laravel things with peeps.

Thoughts?

**Comment by sschlein** [comment]
Whoop whoop: https://tinkerwell.app/release/2.5.0
