### ISSUE TITLE
Tinkerwell 2.3.0 AppImage - squashfs image error

### ISSUE THREAD

**Issue by georanma** [beyondcode/tinkerwell-suggestions#129]
`Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
`
Anyone else seeing this? 

Ubuntu 19.10

**Comment by georanma** [comment]
TInkerwell 2.3.1 addresses this issue. Closing this out.

**Comment by Blair2004** [comment]
This has happened to me because the AppImage was corrupted. So downloading from beyondco.de dashboard should fix that.
