### ISSUE TITLE
Windows version 😉

### ISSUE THREAD

**Issue by spresnac** [beyondcode/tinkerwell-suggestions#13]

**Comment by niladam** [comment]
Whoa, i don't usually comment and instead use the reaction, but on this ? I have to!:)

**Comment by sschlein** [comment]
Released today 🎉

**Comment by spresnac** [comment]
https://giphy.com/gifs/dancing-party-birthday-MS3XuWjQV1FiU
![image](https://user-images.githubusercontent.com/3299107/73000933-eb317d80-3e01-11ea-9b7e-25c89d5131f2.png)
