### ISSUE TITLE
Error Database Connection [Local-Wordpress] - MacOS

### ISSUE THREAD

**Issue by Devlop-er** [beyondcode/tinkerwell-suggestions#133]
Hi I'm trying to use a Wordpress function such as: site_url()
it return the html database error page.

[X] The working directory is properly defined
[X] My php folder is correctly found

Do you have any idea on what's going on ?
Thanks for your help

**Comment by andrefredette** [comment]
I had the same issue, which I resolved by using the local Socket path as the DB_HOST rather than "localhost" or "127.0.0.1". Using the format here https://snippets.khromov.se/using-wordpress-with-mysql-unix-socket/ try updating your wp-config.php file with the socket info and see if that works.

**Comment by Devlop-er** [comment]
Perfect thanks @andrefredette  =)
