### ISSUE TITLE
Tinkerwell 2.4 Fatal error: Declaration of Application::handle() must be compatible with HttpKernelInterface::handle()

### ISSUE THREAD

**Issue by MasterRO94** [beyondcode/tinkerwell-suggestions#140]
I have installed a fresh version of Tinkerwell because of previous version didn't update automatically and got an error with empty left side of app.

```php
Fatal error: Declaration of Illuminate\Foundation\Application::handle(Symfony\Component\HttpFoundation\Request $request, $type = self::MASTER_REQUEST, $catch = true) must be compatible with Symfony\Component\HttpKernel\HttpKernelInterface::handle(Symfony\Component\HttpFoundation\Request $request, int $type = self::MASTER_REQUEST, bool $catch = true) 
in /Applications/Tinkerwell.app/Contents/Resources/Laravel/7.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 29
```

**Comment by jzpeepz** [comment]
I had this same issue.

Turns out that `/usr/bin/php` on my  machine was version 7.1.23.

Laravel 7 requires 7.2.5 I believe.

I had version 7.3.6 installed at `/usr/local/opt/php@7.3/bin/php`

I changed Tinkerwell > Preferences > Advanced > PHP Binary to the 7.3.6 path and everything worked.

**Comment by MasterRO94** [comment]
Yep. Thanks. This had solved the problem.

**Comment by paul-gene** [comment]
I had the same issue. How can I use Tinkerwell not in "laravel mode"?

**Comment by pixdrift** [comment]
I have the same question as @paul-gene. Is there a way to use this without the Laravel requirement? I would like to test code against earlier versions of PHP 7.
