### ISSUE TITLE
Tinkerwell 2.5.0 not working for Laravel 7

### ISSUE THREAD

**Issue by quaidesbalises** [beyondcode/tinkerwell-suggestions#142]
Hi,

I just installed the 2.5.0 new release. Previously I had the 1.* version. 

When I am on a Laravel 7 app (the default one or one I installed) I got this error message in the output : 

```php

PHP Warning:  PHP Startup: Unable to load dynamic library 
'/usr/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so' -
dlopen(/usr/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so, 0x0009): 
dlopen(): file not found: /usr/lib/php/extensions/no-debug-non-zts-20160303/mcrypt.so 
in Unknown on line 0
PHP Fatal error:  Declaration of 
Illuminate\Foundation\Application::handle(Symfony\Component\HttpFoundation\Request
$request, $type = self::MASTER_REQUEST, $catch = true) must be compatible with
Symfony\Component\HttpKernel\HttpKernelInterface::handle(
Symfony\Component\HttpFoundation\Request $request, 
int $type = self::MASTER_REQUEST, bool $catch = true) in 
/Applications/Tinkerwell.app/Contents/Resources/Laravel/7.0/vendor/laravel/framework/src/
Illuminate/Foundation/Application.php on line 29

```

However, the app is working well in the browser. Artisan is working well in command line.
I'm running on PHP 7.2.9.

What do I suppose to do to solve it ?

**Comment by mpociot** [comment]
Are you using the correct PHP binary in the tinkerwell settings?

**Comment by quaidesbalises** [comment]
Thanks Marcel, you're right. I change it to /usr/local/bin/php and that works. 
My bad, didn't expect that issue cause the previous version works by default.

**Comment by mpociot** [comment]
Yeah, I try to detect the correct PHP binary, but sometimes it doesn't work automatically :)

**Comment by AdeebTwait** [comment]
I changed it also to /usr/local/bin/php and it works!! Thank you @mpociot.
