### ISSUE TITLE
Cannot update from 2.4.0 to 2.5

### ISSUE THREAD

**Issue by hcancelik** [beyondcode/tinkerwell-suggestions#147]
I get a notification "A new update is ready to install" notification but the app doesn't get updated on exit. The only way to update the app is to re-download it.

**Comment by mpociot** [comment]
Yeah, I am fighting this problem since a couple of releases. I'm still trying to figure out why it's happening. I'm going to close this one, as I am looking into it. 
It helped me to keep the app closed a while once I saw the notification.
