### ISSUE TITLE
Symbols appearing at end of output

### ISSUE THREAD

**Issue by ryangjchandler** [beyondcode/tinkerwell-suggestions#15]
<img width="638" alt="Screen Shot 2019-11-20 at 11 44 08 AM" src="https://user-images.githubusercontent.com/41837763/69236317-2c4fac00-0b8b-11ea-8d15-560a29d8783d.png">

Not sure what causes this, but only been happening for me since 1.2 update.

**Comment by mpociot** [comment]
@ryangjchandler This only happens when you run code via SSH, right?

**Comment by ryangjchandler** [comment]
> @ryangjchandler This only happens when you run code via SSH, right?

That's right, yes

**Comment by sschlein** [comment]
Is this still the case with 2.x?

**Comment by sschlein** [comment]
Closed for now
