### ISSUE TITLE
Shortcut key for query inspection on windows?

### ISSUE THREAD

**Issue by xitox97** [beyondcode/tinkerwell-suggestions#151]
Anyone know what is the shortcut key on windows to inspect query? Cannot seem to find it.

**Comment by decadence** [comment]
@xitox97 what is the answer to this?

**Comment by xitox97** [comment]
@decadence ctrl + shift + r. It will pop out "Replace character". You just press escape. Make sure you highlight the syntax first.

**Comment by decadence** [comment]
Thanks. Will try that.

**Comment by decadence** [comment]
@xitox97 I do something wrong because I don't get any new info.

Let's say I have
```php
Project::all();
```

I selected this text, press  Ctrl+Shift+R  and then Escape.
All I got is
![image](https://user-images.githubusercontent.com/1434668/77313354-c29c0600-6d14-11ea-96d5-6fcfac1f9f17.png)

**Comment by xitox97** [comment]
@decadence which php version that you use? are you using php inside xampp/laragon?

**Comment by decadence** [comment]
@xitox97 I use PHP 7.2 and OpenServer (russian WAMP)
