### ISSUE TITLE
not recognize external namespaces

### ISSUE THREAD

**Issue by lucabecchetti** [beyondcode/tinkerwell-suggestions#154]
I have an external repo for models, but it does not work!

![Schermata 2020-03-17 alle 10 19 03](https://user-images.githubusercontent.com/16253548/76841385-fc629d80-6838-11ea-9e5f-cbc179fed47b.png)

Can you help me?

**Comment by sschlein** [comment]
Hey, it looks like you are in the default Laravel project instead of your local directory ;-)

**Comment by lucabecchetti** [comment]
@sschlein sorry, this issue now:
![Schermata 2020-03-17 alle 10 27 15](https://user-images.githubusercontent.com/16253548/76842061-f91be180-6839-11ea-89dc-e2004595e287.png)

**Comment by lucabecchetti** [comment]
up

**Comment by lucabecchetti** [comment]
fixed changing localhost to 127.0.0.1 on .env DB_HOST
