### ISSUE TITLE
Update doesn't always work

### ISSUE THREAD

**Issue by wrabit** [beyondcode/tinkerwell-suggestions#159]
The update notification comes up.

![image](https://user-images.githubusercontent.com/5918271/77081837-88bcbe00-69fb-11ea-8b20-77f4bbf77052.png)

I give it 30 seconds, in case it needs to download the files, restart and the message appears again.

**Comment by sschlein** [comment]
Duplicate https://github.com/beyondcode/tinkerwell-suggestions/issues/101#issuecomment-601220731

(please download 2.6 from the website, this update also fixes the auto-updater)
