### ISSUE TITLE
Tinkerwell <> Xdebug

### ISSUE THREAD

**Issue by ARNHOE** [beyondcode/tinkerwell-suggestions#167]
Hi guys,

I am trying to use xdebug with Tinkerwell. For some reason it isn't being triggered. The weird part is, that when I use tinker via the terminal, it does trigger.

Below my xdebug configuration ini.

```
;XDebug
zend_extension="/usr/local/lib/php/pecl/20190902/xdebug.so"
xdebug.remote_autostart=1
xdebug.default_enable=1
xdebug.remote_port=9001
xdebug.remote_host=127.0.0.1
xdebug.remote_connect_back=1
xdebug.remote_enable=1
xdebug.idekey=PHPSTORM
```

Any chance you could guide me in the right direction?

**Comment by zembrowski** [comment]
`which php` vs Preferences > Advanced > PHP binary path

**Comment by ARNHOE** [comment]
I thought the same, but unfortunately this hasn't solved it.
