### ISSUE TITLE
Tinkerwell loads a different PHP version

### ISSUE THREAD

**Issue by abishekrsrikaanth** [beyondcode/tinkerwell-suggestions#168]
I am on the latest version of Tinkerwell App. I have PHP 7.3 and 7.4 installed on my mac and I seem to be having an issue with Tinkerwell and am not sure how to fix this. Anybody else has a similar issue?

So, when I launch a `terminal/iTerm` and run `php -v`, I get `7.4.3`, but when I run tinkerwell and get the PHP version by running `phpinfo();`, I get 7.3.11. 

I did look up the locations for both executions and they show the same folder for the PHP binary.

Here is a screenshot attached.

<img width="1100" alt="Screen Shot 2020-03-24 at 6 11 21 PM" src="https://user-images.githubusercontent.com/1639302/77426890-6e1f8600-6dfb-11ea-9dd4-fb412f03465a.png">

**Comment by appotter** [comment]
How did you solve that?

**Comment by sonicfive** [comment]
This is still a problem for me

**Comment by noitran** [comment]
Probably just write `which php` in your terminal.
It will output something like

/usr/local/bin/php

Change it in tinkerwell and you are good to go...
