### ISSUE TITLE
Word wrap option

### ISSUE THREAD

**Issue by minthemiddle** [beyondcode/tinkerwell-suggestions#17]
It would be nice if Tinkerwell had an option to automatically wrap lines if output exceeds available space.

I would prefer that over scrolling horizontally. Others may disagree, so a checkbox in settings to choose would be ideal.

![Bildschirmfoto 2019-11-20 um 13 16 51](https://user-images.githubusercontent.com/1950766/69238392-290eed00-0b98-11ea-8cba-6b03df20a21a.png)

**Comment by sschlein** [comment]
Released today with the 2.0 version 🎉
