### ISSUE TITLE
The server requested authentication method unknown to the client

### ISSUE THREAD

**Issue by bencarter78** [beyondcode/tinkerwell-suggestions#173]
Hello

I'm new to Tinkerwell and trying to understand why I'm getting the following error when using the Tinkerwell Default or when I load my app into the application. I'm using MySQL 8 with the latest Laravel install (7.3.0)

I'm trying to run `App\User::all()` and get...

`Illuminate/Database/QueryException with message 'SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from `users` limit 1)`

My application works fine

Any ideas?

**Comment by desaintflorent** [comment]
I had the same problem and was using Valet and Homestead. 
it's probably that you need to change the default Php binary in tinker well settings. It should be /usr/local/bin/php not /usr/bin/php
To change it, in Tinkerwell App go to the preferences/advanced and click select. Then Press Command+Shift+G to open the dialogue box and past /usr/local/bin/php.

**Comment by bencarter78** [comment]
@desaintflorent dude that was exactly what it was! Thanks so much for your help!

**Comment by mikeerickson** [comment]
This is one of those things that should be in the FAQ as this seems to be a problem for many first timers to Tinkerwell
