### ISSUE TITLE
SQL Errors on query

### ISSUE THREAD

**Issue by davsaniuv** [beyondcode/tinkerwell-suggestions#181]
im using version 2.6.0 and im getting this error, im using mac os 10.15.4 i've opened my folder

[!] Aliasing 'User' to 'App\Models\User' for this Tinker session.
Illuminate/Database/QueryException with message 'SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `users`)'

here its the query : User::all();

**Comment by dragonfire1119** [comment]
Check you PHP Executable in Preferences > Advanced

**Comment by davsaniuv** [comment]
im using homebrew php but i cant find the path for that file

**Comment by dragonfire1119** [comment]
Use ``which php`` then you will find it.

**Comment by davsaniuv** [comment]
it works, thanks!

**Comment by dragonfire1119** [comment]
@davsaniuv You're welcome!

**Comment by mikeerickson** [comment]
Yet again, a good vote to put this frequently asked question in support FAQ

**Comment by sschlein** [comment]
THere you go: https://tinkerwell.app/faq/#jump-to-16
