### ISSUE TITLE
Issues on OSX Yosemite and SSH 

### ISSUE THREAD

**Issue by mikhailstoyanov** [beyondcode/tinkerwell-suggestions#183]
Hi there,

I've just purchased Tinkerwell but can't make it work via SSH - it crashes as soon as I click on 'Connect'.  I am running an old version of Yosemite - 10.10.2 (14C109). 

```
20:17:08.627 › Checking for update
(node:2870) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:2870) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
20:17:08.951 › Update for version 2.6.0 is not available (latest version: 2.6.0, downgrade is disallowed).
(node:2905) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:2905) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

```
Any suggestions? 
Thanks in advance
Mikhail

**Comment by sschlein** [comment]
Hi Mikhail,

Tinkerwell needs at least 10.13 - we haven't tested older versions. If you can't upgrade, we can give you a refund. Just send an email to support@beyondco.de :)

**Comment by mikhailstoyanov** [comment]
Thank you Sebastian! No need to refund, will keep the license for future use.
However, I think it would be good if this requirement is specified on the website.
Big ups for the tool! :)
