### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by ryangjchandler** [beyondcode/tinkerwell-suggestions#185]
I think it would be neat to add support for custom themes via either a custom CSS stylesheet, or just hex codes that can be entered in preferences. Can't imagine it would too hard to do since it's just CSS styled anyway

**Comment by sschlein** [comment]
Unfortunately, it requires a rewrite of multiple parts of the app that have been ported from the version 1 Swift version. That is something that we could introduce with a rewritten version 3 and a lot of documentation. 

That said, we don't have plans to do this in the near future and so I'm closing this issue for now :)
