### ISSUE TITLE
Can't download tinkerwell app from beyondcode dashboard

### ISSUE THREAD

**Issue by apsbd** [beyondcode/tinkerwell-suggestions#187]
It keeps me in a loop. When I try to download it from https://tinkerwell.app/management it redirects me to https://phppackagedevelopment.com/dashboard, and when I click on available licenses, it redirects me to tinkerwell.app homepage.

**Comment by sschlein** [comment]
That's likely a DNS issue on your end. Can you try to access it from https://beyondco.de/login ?

**Comment by sschlein** [comment]
The link for the download - logged in via license or account should be https://beyondco.de/licenses/tinkerwell

**Comment by apsbd** [comment]
I tried. but when I clicked Get Tinkerwell from available licenses, it redirects me to tinkerwell.app home page 
    On Wednesday, 8 April 2020, 12:39:02 pm GMT+6, Sebastian Schlein <notifications@github.com> wrote:  
 
 


That's likely a DNS issue on your end. Can you try to access it from https://beyondco.de/login ?

**Comment by apsbd** [comment]
this works :) 
    On Wednesday, 8 April 2020, 12:39:58 pm GMT+6, Sebastian Schlein <notifications@github.com> wrote:  
 
 


The link for the download - logged in via license or account should be https://beyondco.de/licenses/tinkerwell

**Comment by apsbd** [comment]
but Build a Chatbot and Get Helo doesn't work
    On Wednesday, 8 April 2020, 12:42:11 pm GMT+6, Mohiuddin Ahmed <mohiuddin_ahmed_07@yahoo.com> wrote:  
 
  this works :) 
    On Wednesday, 8 April 2020, 12:39:58 pm GMT+6, Sebastian Schlein <notifications@github.com> wrote:  
 
 


The link for the download - logged in via license or account should be https://beyondco.de/licenses/tinkerwell

**Comment by apsbd** [comment]
also after download the tinkerwell app. it is asking for activation code. but, I can't see any in the beyondcode dashboard.

**Comment by sschlein** [comment]
Can you send me some screenshots to support@beyondco.de ? That sounds really weird.

**Comment by apsbd** [comment]
Here's what I can see in my beyondcode dashboard. and when I click on those buttons, I just redirected to it's landing page. that's it    On Wednesday, 8 April 2020, 12:49:06 pm GMT+6, Sebastian Schlein <notifications@github.com> wrote:  
 
 


Can you send me some screenshots to support@beyondco.de ? That sounds really weird.

**Comment by sschlein** [comment]
Continued via 1:1 support, seems to be a stucked order.
