### ISSUE TITLE
Code editor section invisible!

### ISSUE THREAD

**Issue by N-Molham** [beyondcode/tinkerwell-suggestions#189]
Hello @mpociot ,

I am having a problem is the code editor section is completely hidden in CLI mode and I can't figure out how to get it back.

I tried to uninstall and re-install the app but with the same issue!

See recording below:

![2020-04-13_19-55-55](https://user-images.githubusercontent.com/3770036/79145404-e0fb9b80-7dc0-11ea-814f-fd2404526b46.gif)

**Comment by sschlein** [comment]
Hey, 

it looks like you are watching a file (should be at "File") and so you don't need the Tinkerwell editor there. To bring it back, there should be a "unwatch file" option in the File menu :)

**Comment by N-Molham** [comment]
Thanks @sschlein for the quick reply,

I think there was a glitch in the app as at first I didn't have the option to "Stop Watching File" as I wan't watching a file, although after I watched a file and stopped watching it, the code editor came back.

Thanks
