### ISSUE TITLE
Framework agnostic

### ISSUE THREAD

**Issue by m50** [beyondcode/tinkerwell-suggestions#19]
Instead of trying to load up a tinker session, it would be really awesome to just load the vendor autoload file, and then let you work from there. 

If it's detected that there is a bootstrap/app.php file or an artisan file or whatever, then load it up as if it's laravel.

Alternatively, you could also have a "bootstrap" snippet that gets saved into the `.tinkerwell` file that would boot strap your framework. So if you call a snippet bootstrap, that will run for every other snippet.

**Comment by sschlein** [comment]
This has been released with today's 2.0 release. We'll publish a tutorial about writing custom drivers shortly :)
