### ISSUE TITLE
Ctrl/cmd + enter to evaluate script

### ISSUE THREAD

**Issue by kakposoe** [beyondcode/tinkerwell-suggestions#192]
Thank you for tinkerwell. It is a great application and now integrated into my development process.

I have recently unchecked the `auto evaluate script` option within the tinkerwell settings so now it requires a button click to evaluate the script.

I wanted to know if there were any plans (or thoughts) for adding a `ctrl/cmd + enter` shortcut to evaluate the script?

Thanks.

**Comment by mikeybeck** [comment]
Are you aware of the `ctrl/cmd + R` run shortcut?

**Comment by kakposoe** [comment]
@mikeybeck Thank you very much, I wasn't aware of this. Will close this issue.
