### ISSUE TITLE
Allow ⌘+W to close window

### ISSUE THREAD

**Issue by bakerkretzmar** [beyondcode/tinkerwell-suggestions#20]
⌘+W is pretty standard in macOS for closing the open window and/or tab, right now in Tinkerwell you can close a tab with it but not the whole window.

**Comment by mpociot** [comment]
This will be released with 1.3

**Comment by adriaanzon** [comment]
I'm on version 2.2.1 and ⌘W isn't working for me, as well as some other common macOS shortcuts like ⌃⌘F to enter fullscreen.

**Comment by nickturrietta** [comment]
Any chance this behavior can be made optional and toggleable by the user under "Preferences"?

Example of how Firefox does it:

![screencap](https://user-images.githubusercontent.com/6426374/100798400-77c0ab00-33d8-11eb-808b-116d513867c0.jpg)
