### ISSUE TITLE
Quick open for multiple projects.

### ISSUE THREAD

**Issue by Hypnopompia** [beyondcode/tinkerwell-suggestions#21]
When working on multiple projects, it would be nice if Tinkerwell remembered the different paths to those projects and had an option to quickly open a new tab for one of those projects instead of having to ⌘+O and navigate to the directory every time. Almost like a recently opened list, or maybe something more formal that could be managed with the ability to add and remove projects.

**Comment by Hypnopompia** [comment]
I really like how sublime text and sublime merge handles this with their quick project switcher.

**Comment by sschlein** [comment]
Recently opened projects sound like a good addition and we also have this for SSH connections. Not sure if the quick open is very common.

**Comment by sschlein** [comment]
There is a more specific issue for "Recent Projects", I'm closing this one and let's follow up in the other issue to get this done.
