### ISSUE TITLE
Using .pem keys

### ISSUE THREAD

**Issue by cyrodjohn** [beyondcode/tinkerwell-suggestions#25]
Support for SSH connection using .pem key

**Comment by klaasgeldof** [comment]
Need this! 😃

**Comment by sschlein** [comment]
It took a while but I have seen reports that pem files are working with v2. We are using a different SSH library there. Can someone confirm this?

**Comment by klaasgeldof** [comment]
Yes, works like a charm!

**Comment by sschlein** [comment]
We'll replace the ssh lib with a new one that is more reliable anyway 😬 But it also supports pem files
