### ISSUE TITLE
Install first party packages

### ISSUE THREAD

**Issue by driesvints** [beyondcode/tinkerwell-suggestions#26]
It would be absolutely insane if you could automate the installation of first party packages.

For example, automate the installation of Dusk into the default shipped Laravel app

- Run `composer require --dev laravel/dusk`
- Run `php artisan dusk:install`

So you can Tinker with it.

I regularly have to set up test apps to debug issues with the libraries so this would be a huge timesaver for me 👍

**Comment by sschlein** [comment]
Are there more people with the issue or is this a Laravel LLC specific one? :)

**Comment by driesvints** [comment]
Don't know. I think it would be handy but can't say for other people.

**Comment by sschlein** [comment]
We have removed the package installer in version 2.0 because it was hardly used. So I'm closing this issue now 🙈
