### ISSUE TITLE
Integrate with Valet

### ISSUE THREAD

**Issue by driesvints** [beyondcode/tinkerwell-suggestions#27]
Allow to easily integrate with valet so you get a test url where you can test out the default installed Laravel app. I realize this goes a bit beyond what Tinkerwell is meant for but just checking if there are any thoughts on this from you?

**Comment by vmitchell85** [comment]
I think it'd be nice to be able to quickly open sites that were registered with Valet.

Based on the `valet paths` command you can find the directories registered with valet and allow sites in those directories to be quickly opened. Or the sites using `valet links`.

**Comment by sschlein** [comment]
I'm closing this issue because I don't think it could become a priority anytime soon. Tinkerwell is evolving fast and became cross-platform since the valet idea came up. We focus on cross-platform ideas before we might add macOS specific features again :)
