### ISSUE TITLE
Command Palette

### ISSUE THREAD

**Issue by vmitchell85** [beyondcode/tinkerwell-suggestions#29]
It would be very convenient to be able to keep your hands on the keyboard to do a number of different things. Similar to most text editors, and other programs like TablePlus you can press a keystroke (Command + P) to run different commands.

Some ideas for things you could do via a command palette:
- Open Forge sites in Tinkerwell
- Run menu commands (install composer package, see queries, etc)
- Open local sites (this one I think would be best with some Laravel Valet integration, I've commented on #27 )

**Comment by sschlein** [comment]
I really like the idea but I'm afraid that this is a lot of work initially. I'm closing this issue because I don't think it will become a priority in the near future - but that's something I'd like to have myself and might implement it later this year.
