### ISSUE TITLE
Comment/uncomment lines via hotkey

### ISSUE THREAD

**Issue by sschlein** [beyondcode/tinkerwell-suggestions#3]

**Comment by ryangjchandler** [comment]
+1

**Comment by mpociot** [comment]
We will support sublime text keybindings in the next release 👍

**Comment by mpociot** [comment]
This will be added in version 1.3

**Comment by rockymontana** [comment]
Is this added? It'd be nice to be able to set the shortcut manually as not all keyboard has easy access to / (on Swedish keyboards the / is Shift+7), plus that comments is cmd+shift+c in my muscle memory. Being able to override the shortcut would be very sugar sweet for these two reasons :-)

**Comment by desaintflorent** [comment]
Can somebody tell me how to comment in tinkerwell ? I tried everything ( sublime or VS code ) but this doesn't seem to be implemented...
I have an azerty keyboard.

**Comment by 0ly** [comment]
> Can somebody tell me how to comment in tinkerwell ? I tried everything ( sublime or VS code ) but this doesn't seem to be implemented...
> I have an azerty keyboard.

On a mac: command + /

**Comment by desaintflorent** [comment]
> On a mac: command + /

This is what I do on Vs Code with my azerty keyboard on a mac. But in tinkerwell it's not working. 
@0ly  Can you confirm that it's working for you and that you have an azerty keyboard ?

**Comment by koernchen02** [comment]
I'm using tinkerwell on archlinux and a wayland WM called sway  and for me none of the common shortcuts are working...
I'm running version 2.13!
