### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by repat** [beyondcode/tinkerwell-suggestions#32]
It would be cool to have a Ctrl/Cmd + F functionality for both sides. Useful e.g. if you're dissecting a big array like an API answer. But also, to find certain pieces in the code on the left side.

**Comment by mpociot** [comment]
![image](https://user-images.githubusercontent.com/804684/74814042-b9271480-52f6-11ea-9d97-b4cea951e63c.png)

Coming in the next release 👍
