### ISSUE TITLE
Unable to connect to Vagrant box using SSH

### ISSUE THREAD

**Issue by AALMA** [beyondcode/tinkerwell-suggestions#35]
I, and another member of my team, are unable to connect to our vagrant boxes using SSH. We can use the same exact connection options from the terminal and it works just fine but when we attempt to connect using the SSH feature in Tinkerwell we get the following error:

![Screen Shot 2019-11-21 at 8 23 10 AM](https://user-images.githubusercontent.com/5289607/69558663-9a72e500-0f76-11ea-8ba9-5a2be6476581.png)

I can assure you there are no spaces or any issues with the settings specified. Have even copied and pasted from the working command line command just to be sure.

At least one other member of our team is able to connect using Tinkerwell and we have yet to identify anything different between our configurations. 

One clue may be that the two of us with issues connecting are both using newer MacBooks, setup in the past month or so.

Any help with this would be greatly appreciated. I just came from another job where I was able to use Tinkerwell and found it really helpful so I'd love to be able to use it with this one as well.

**Comment by sschlein** [comment]
I just added the standard Homestead configuration to the FAQs here: https://tinkerwell.app/faq

Many thanks to Nathan for this Tweet: https://twitter.com/un4tunatetoast/status/1193918727953244161

Does this guide you in the right direction? error 1 is just a generic one and could be everything - it's mostly related to the wrong SSH key.

**Comment by AALMA** [comment]
Thanks for the response @sschlein, unfortunately we're not using homestead for our setup. 
I can use this to connect from command line `ssh vagrant@192.168.9.9 -I path_to_private_key` but those exact same settings in Tinkerwell don't work so it cannot be a problem with the settings I'm using. Is there anyplace I could check for a log that shows the actual ssh error?

**Comment by AALMA** [comment]
I just had another member of my team (the one who is able to connect) send me the public key for our private key that we use to connect to our vagrant box. I put that in the same directory as the private key and it works.

I am assuming you're using [this library for SSH ](https://github.com/jakeheis/Shout#private-key) given the error message.

It sounds like there should be option for not specifying the public key but Tinkerwell is always specifying it and in this case it didn't exist.

**Comment by sschlein** [comment]
Ohh, that's actually right. I didn't expect a shared private key without a related public key.

**Comment by sschlein** [comment]
Added this to the FAQ section and to #1

**Comment by rasmuscnielsen** [comment]
@sschlein 
Not sure if I should post it here, or create a new issue. But: I too am experiencing the same SSH connectivity issues to all forge servers.

I checked, and I have both private + public key in the same folder. Any other suggestions why this may happen? 

![Skærmbillede 2019-11-26 kl  13 17 23](https://user-images.githubusercontent.com/8465957/69632332-2fe1a800-104f-11ea-9888-e7550ca5b1f3.png)
![image](https://user-images.githubusercontent.com/8465957/69631939-bba70480-104e-11ea-90eb-a22b954bea05.png)
![image](https://user-images.githubusercontent.com/8465957/69631974-c6fa3000-104e-11ea-8c76-b08ce61049c1.png)

**Comment by Vusys** [comment]
@sschlein 

I have the same problem as @rasmuscnielsen except I'm trying to get into my Homestead box. Public and private key are in the same directory. I have no problems SSHing into the box in a terminal.

**Comment by kristremblay** [comment]
@sschlein 

I am having the same issue as @Vusys on connecting to the homestead box.  I can connect via `ssh vagrant@192.168.152.161` but using the same settings in Tinkerwell yields a socket error 1.  Private and public key are in the same directory.

**Comment by sschlein** [comment]
Is anyone using passphrases for their SSH key? If yes, this goes into the passphrase field. If the vagrant machine is password-protected, that can be an issue, I think we don't have a solution for this yet.

Can you post screenshots of your connection like @rasmuscnielsen did?

@rasmuscnielsen do you have you server behind something like cloudflare? If yes, the domain will not get resolved correctly and you have to add an ip address here. We'll introduce labels with the next version so that this is handled better

**Comment by kristremblay** [comment]
@sschlein in my case there is no passphrase on the box.  This is on my local machine.

![image](https://user-images.githubusercontent.com/7587183/70552223-8dd9b980-1b3e-11ea-9aa4-0cec91e793af.png)

**Comment by kristremblay** [comment]
@sschlein Inadvertently used a key that did in fact have a passphrase on it.

**Comment by Vusys** [comment]
The passphrase solved it for me. Hooray. Thank you very much @sschlein. Would suggest that gets put in the FAQ because I had no idea. 😭

**Comment by sschlein** [comment]
I added the passphrase to the FAQ for SSH connection issues. We'll definitely make this clearer in the new version... sorry.

Also: If you have support questions, you likely get a much faster response if you mail us at support@beyondco.de. This repository is mostly for suggestions so we don't look at it daily 🙈
