### ISSUE TITLE
Base16 Tomorrow theme

### ISSUE THREAD

**Issue by pryley** [beyondcode/tinkerwell-suggestions#36]
It would be nice to have the [Base 16 Tomorrow](http://chriskempson.com/projects/base16/) colour scheme (for syntax highlighting only, see #37).

**Comment by sschlein** [comment]
Will be in 1.3 (but the toolbar is not skinable yet so get comfortable with keyboard shortcuts ;-)

<img width="1112" alt="Bildschirmfoto 2019-11-27 um 17 38 44" src="https://user-images.githubusercontent.com/2911113/69742322-e1123c00-113c-11ea-85c4-9c907fc7df40.png">

**Comment by mpociot** [comment]
Just to clarify: The toolbar will still be in there, the theme just doesn't look nice in combination with the toolbar
