### ISSUE TITLE
PhpStorm tinkering queries.

### ISSUE THREAD

**Issue by frogeyedman** [beyondcode/tinkerwell-suggestions#38]
Is there a way to execute queries with the PhpStorm Tinkerwell plugin when using a Vagrant machine? I ran into the following issue:

![tinkerwell](https://user-images.githubusercontent.com/26088905/69721878-17889080-1116-11ea-9bf4-99a5c0e19281.png)

**Comment by sschlein** [comment]
Hi – the IDE plugins don't work with SSH connections and we don't know if this will ever be possible. I'll add something to the FAQ shortly https://tinkerwell.app/faq

Sorry :(
