### ISSUE TITLE
AppleScript

### ISSUE THREAD

**Issue by jbrooksuk** [beyondcode/tinkerwell-suggestions#39]
Support for AppleScript would allow us to create Alfred Workflows.

For example, I use Tinkerwell to support Forge. It'd be great if I could use an Alfred Workflow to connect to the Forge server automatically and supply some code based on variables.

**Comment by sschlein** [comment]
How would this work in general?

**Comment by sschlein** [comment]
Closed due to inactivity, sorry ;-)
