### ISSUE TITLE
Make it work with Vapor

### ISSUE THREAD

**Issue by clmntgr** [beyondcode/tinkerwell-suggestions#41]
Not sure if this is possible, but it will be awesome to use this with Vapor.

Maybe launch a job on each command or launch the commands from a jumpbox.

**Comment by sschlein** [comment]
We put some thought into this but can't come up with a way to do it in the near future. So I'm closing this for now (even if I would like to have it myself..)

**Comment by haoxi911** [comment]
Would this be helpful? https://blog.laravel.com/vapor-tinker-command
