### ISSUE TITLE
add default packages

### ISSUE THREAD

**Issue by marijnbent** [beyondcode/tinkerwell-suggestions#42]
I'm adding "use carbon/carbon" quite often to new tinker screens. Would be nice to add some default ones which are loaded if available

**Comment by mpociot** [comment]
The next version of Tinkerwell will allow you to create custom "drivers" where you can modify bootstrapping logic. Then you could do something like this:

```php
<?php

class CustomTinkerwellDriver extends LaravelTinkerwellDriver
{

    public function bootstrap($projectPath)
    {
        parent::bootstrap($projectPath);

        class_alias(Carbon\Carbon::class, "Carbon");
    }
}
```
