### ISSUE TITLE
Shortcut Keys: Command + 1 - 9 to focus open tabs. Command + Enter to run code

### ISSUE THREAD

**Issue by drehimself** [beyondcode/tinkerwell-suggestions#44]
Command + 1 - 9 to focus open tabs is pretty standard in web browsers/iTerm.

Command + Enter to run code (if it doesn't interfere with upcoming code editor keymappings). Most GraphQL clients have both Command + R and Command + Enter to run code.

Tinkerwell is awesome! 😎

**Comment by sampittman** [comment]
Command + Enter to run code would be an awesome addition!

**Comment by mpociot** [comment]
You will be able to switch tabs using cmd + 1-9 in the next release.
Cmd+Enter doesn't work because of the sublime key bindings we use

**Comment by webboty** [comment]
Awesome App ... is there any other way to trigger to run the code via keyboard?
I Don't want to use the mouse. 

I do not like the immediate execution of code as we type (an option of tinkerwell) in database manipulation tests.

**Comment by sschlein** [comment]
@webboty You can run code by pressing CMD/CTRL + R and disable the auto evaluation in the settings or via the shortcut. Here is the list of shortcuts of Tinkerwell: https://beyondco.de/docs/tinkerwell/advanced-usage/shortcuts
