### ISSUE TITLE
save session / remember on close + project manager

### ISSUE THREAD

**Issue by vesper8** [beyondcode/tinkerwell-suggestions#48]
currently if I open a bunch of tabs and load different working projects in each tab. If I close Tinkerwell and re-open I lose everything and have to start all over. I would prefer if it worked like Sublime/many other tools where there's an option to remember all the opened tabs and save the state. Optionally I could save the session/workspace and load it back

Would also like some kind of Project Manager that works similarly to https://github.com/alefragnani/vscode-project-manager where I can have all my projects saved in an xml somewhere, which I can possibly populate myself programatically as I do in vscode.. so I can very quickly hit a shortcut, see a list of all my projects, use an autocomplete search and quickly switch to one of my many projects without having to browse for it manually each time

**Comment by klaasgeldof** [comment]
@ #43

**Comment by mpociot** [comment]
Closing this because it's basically a duplicate of #43 - which will be released soon 🤞
