### ISSUE TITLE
Keyboard Shortcut for "Enter Full Screen" and "Exit Full Screen"

### ISSUE THREAD

**Issue by simensen** [beyondcode/tinkerwell-suggestions#51]
It would be great to be able to pop into and out of full screen quickly. On mac, it seems like "^+Command+F" is pretty standard, but iTerm uses "Command+Return".

**Comment by mpociot** [comment]
This will be added in the next Tinkerwell release.

**Comment by sschlein** [comment]
Also available within the menu + shortcut in next 2.x release
