### ISSUE TITLE
Keyboard Shortcut for "Show Toolbar"

### ISSUE THREAD

**Issue by simensen** [beyondcode/tinkerwell-suggestions#52]
This is something that is nice to have access to from time to time but also something that clutters up the display with stuff you might not be using a lot. There is a workaround as the standard "Command+," shortcut puts the "Show Toolbar" front and center (if not at the bottom), but it would be nice if this could follow some conventions where it can easily be brought to foreground/dismissed.

**Comment by sschlein** [comment]
CMD+SHIFT+T with next release
