### ISSUE TITLE
Tweak auto-code-formatting to not trim trailing commas after last element in an array

### ISSUE THREAD

**Issue by simensen** [beyondcode/tinkerwell-suggestions#53]
I haven't really cared that my code has been reformatted until I ran into this specific issue the other day. :) You can see my problem demonstrated here:

https://www.youtube.com/watch?v=qjhwXKygbjY&feature=youtu.be&t=2052

(that section ends by ~35 minutes 15 seconds. :))

TL;DW When the code is reformatted, it trims the trailing comma from arrays. These needlessly causes errors if you comment and then uncomment the last item in an array.

Could be related to #7, though this could be considered more of a bug fix vs having the ability to disable auto-code-formatting is more of a feature.

**Comment by mpociot** [comment]
Good point. I'm using Prettier with the PHP plugin, so I can just use their trailing comma feature 👍
