### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by tomcoonen** [beyondcode/tinkerwell-suggestions#57]
It would be very helpful to have autocompletion work for directories, files and namespaces.

**Comment by sschlein** [comment]
We recommend using the IDE plugins for auto-completion. 

I know, they don't support SSH connections yet but you get all the benefits of your IDE and can write the code with autocompletion. So we have no plans for autocompletion in Tinkerwell at the moment as there are so many other things we want to do :)
