### ISSUE TITLE
Tech stack

### ISSUE THREAD

**Issue by morrislaptop** [beyondcode/tinkerwell-suggestions#58]
Do you have any details on how you built the macOS app and then ported to iOS / Windows etc.. Is it Electron? I think it would be a great story for indie developers.

**Comment by mpociot** [comment]
Yeah, I plan on writing a blog post about this. The current version is built in Swift, but I am right now finishing the Electron-based version. Otherwise, it simply wouldn't be possible to maintain the codebase for Windows, Linux, and Mac users at the same time for us.
