### ISSUE TITLE
Class 'Psy\ExecutionClosure' not found 

### ISSUE THREAD

**Issue by miagg** [beyondcode/tinkerwell-suggestions#61]
Can't tinker any local project with laravel 5.0 to 5.5.
`php artisan tinker` works normally.

I've tested with php 7.3 & 7.4.
Tinkering with default laravel 6 project works normally.

I'm on Mac OS X Catalina 10.15.2. I run my projects with the latest Laravel Valet.
Any ideas?

**Comment by sschlein** [comment]
Hi @miagg 

I believe you need to upgrade the https://psysh.org/ package that we don't ship with Tinkerwell yet. Starting with the next update in January, this will be bundled with the app and don't require the update via composer.

Best regards

**Comment by OwenMelbz** [comment]
Hi,

Is there an update on this? As it's Feb and we're still hitting the issue on a project using laravel `5.2.45` and tinkerwell version `1.2.0 (5)`

`User::all();`

returns

```                                               
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Psy\ExecutionClosure' not found                                                                            
```


A couple of things I've tried such as.....

`composer update psy/psysh`
`composer require laravel/tinker`
`composer g require psy/psysh:@stable`

All still through the error sadly.

Many thanks, love the tool :)

**Comment by roarkmccolgan** [comment]
I'm getting the same issue too.

Laravel 5.3.31 
Tinkerwell 1.2.0

Thanks
