### ISSUE TITLE
Funky characters when using SSH

### ISSUE THREAD

**Issue by edalzell** [beyondcode/tinkerwell-suggestions#62]
When running a query I get the following at the bottom:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/6069653/71924877-b4424300-3144-11ea-82ce-92233e54732d.png">

**Comment by wyred** [comment]
+1

I have this problem too.

Is your OS language in English or a different language?

**Comment by edalzell** [comment]
English

**Comment by simensen** [comment]
I've only just started using SSH today and I'm seeing this now, too.

**Comment by sschlein** [comment]
Can you please check if this also happens in version 2.0 that was released today? You can download the new version on the Tinkerwell website here: https://tinkerwell.app/download

**Comment by simensen** [comment]
Happy to confirm that I haven't been able to reproduce this with 2.x. Yet. :)
