### ISSUE TITLE
Color codes in output

### ISSUE THREAD

**Issue by ihorvorotnov** [beyondcode/tinkerwell-suggestions#65]
- Tinkerwell Version 1.2.0 (5), macOS Catalina 10.15.2 (19C57)
- PHP 7.2, 7.3, 7.4 (all latest releases of every branch, installed with Homebrew via Valet use command)

`php artisan tinker` works perfectly fine (and `psysh` too btw) invoked from iTerm, Terminal app and PhpStorm terminal/console. But when I run anything in the Tinkerwell app, the output is mixed with cli color codes:

![CleanShot 2020-01-17 at 15 29 10@2x](https://user-images.githubusercontent.com/1066083/72615784-22091e80-393e-11ea-8fa5-bced984c8bba.jpg)

The app is unusable in this state.

**Comment by sschlein** [comment]
That somehow only happens to your install and not for other users.

Can you please install version 2 and check if this still happens? You can download it here: https://tinkerwell.app/releases

**Comment by ihorvorotnov** [comment]
Yup, seems like it's only on my machine - have no idea why. Already installed v2 the day it came out - same messy output.

**Comment by ihorvorotnov** [comment]
Figured it out I had `'colorMode' => \Psy\Configuration::COLOR_MODE_FORCED` set in my `~/.config/psysh/config.php` for whatever reason. Removing this fixed the issue.
