### ISSUE TITLE
Option to change the Run shortcut (Ctrl+R) to something else

### ISSUE THREAD

**Issue by slano** [beyondcode/tinkerwell-suggestions#67]
- Tinkerwell-2.0.0.AppImage on Linux

It would be great if there was an option to change the Ctrl+R shortcut to something else (for example I'm used to Ctrl+Enter a lot)

**Comment by filipedtristao** [comment]
Changing the shortcut to CTRL + ENTER was the first thing I tried to do.

**Comment by mpociot** [comment]
Being able to customize keybindings is not an easy thing to implement. I'll skip it for now and come back to it at a later point.

**Comment by didac-adria** [comment]
+1
