### ISSUE TITLE
PHP binary location doesn't change (but works)

### ISSUE THREAD

**Issue by masterix21** [beyondcode/tinkerwell-suggestions#71]
Hi, there is a problem when you try to change the PHP binary: you must close and open the preferences window again to see the changes.

[tinkerwell-bug-php-version.zip](https://github.com/beyondcode/tinkerwell-suggestions/files/4108159/tinkerwell-bug-php-version.zip)

**Comment by sschlein** [comment]
Should be fixed with the recent release 2.0.1. Restart the app and you get the update automatically :)
