### ISSUE TITLE
VsCode Extension Windows

### ISSUE THREAD

**Issue by tiagosimoesdev** [beyondcode/tinkerwell-suggestions#74]
When selecting Open in tinkerwell or Run with Tinkerwell in vsCode nothing happens ..

**Comment by isaaccubas** [comment]
same problem, recently buy tinkerwell and installed extension in vsCode and nothing happens when selecting open or run in tinkerwell

**Comment by sschlein** [comment]
The recent update broke the VSCode extension - we already submitted a fixed one but it needs to be approved. I hope that this will happen soon.

**Comment by Butochnikov** [comment]
same problem

Error: command 'tinkerwell.run' not found

**Comment by piuscreativebox** [comment]
@sschlein  Why not close this ticket once the approval has come through. To allow people to track when the need to update the vscode plugin arises. Still currently experiencing this problem

**Comment by therealspoljo** [comment]
I am still experiencing the "**Error: command 'tinkerwell.*' not found**" error. 

VSCode v1.43.0
Tinkerwell v2.3.0 (installed with AppImageLauncher)
Tinkerwell for VSCode v2.0.0

**Comment by Draidel** [comment]
same here

**Comment by shahidkarimi** [comment]
Same problem!
![image](https://user-images.githubusercontent.com/4100920/81463417-f3f06880-91d2-11ea-9227-1f275c7ab8d8.png)
