### ISSUE TITLE
Remove "User Default Laravel App" icon

### ISSUE THREAD

**Issue by maks-rafalko** [beyondcode/tinkerwell-suggestions#76]
Since now Tinkerwell uses custom drivers and it's not Laravel-specific anymore, could you please consider removing this icon?

I don't use Laravel at all and this icon is just useless (with all the respect).

**Comment by sschlein** [comment]
It still takes you to the default Laravel app that is included in Tinkerwell. The user base is also 90% Laravel users so there are no plans to remove it anytime soon.
