### ISSUE TITLE
Add an icon of detected driver

### ISSUE THREAD

**Issue by maks-rafalko** [beyondcode/tinkerwell-suggestions#77]
It would be extremely useful if there will be an icon of auto detected driver.

![Tinkerwell - 3](https://user-images.githubusercontent.com/3725595/73128785-aa925980-3fe5-11ea-9fee-b47ed0a4d565.png)

For example if I open a Laravel project - there is a Laravel icon appears. If I open a Symfony project - Symfony icon appears, etc.

**Comment by mpociot** [comment]
Hm..I doubt that we can find an appropriate icon for every driver.
Instead, custom drivers should tell you which application was detected by using the context menu functionality.

![image](https://user-images.githubusercontent.com/804684/73742030-c915f480-474b-11ea-8c6c-66b175c1a5d7.png)

**Comment by maks-rafalko** [comment]
you can show icons for major framework at least. What you are suggesting requires to click, which is not even comparable to what is suggested.

This is the same as when you have a prompt that shows github branch in the terminal:

<img width="437" alt="zsh 2020-02-04 15-52-54" src="https://user-images.githubusercontent.com/3725595/73746558-81509680-4766-11ea-8d16-fd53e0b35a93.png">

Compare it to opening a folder and writing `git branch` & `git status`. DX is much more worse
