### ISSUE TITLE
No way to update? Update notifications?

### ISSUE THREAD

**Issue by edalzell** [beyondcode/tinkerwell-suggestions#78]
I had 2.0.0 and saw that there was a new release, but there is no "Update" menu item nor am I notified of updates.

Can you please add something to make it easy to update?

Thanks!

**Comment by sschlein** [comment]
You get notified if you restart the app :-)

**Comment by edalzell** [comment]
This was on a fresh "open" of the app.

I'll check again on next new release.

**Comment by spielfigur** [comment]
I´ve Version 1.2.0 and it says

```
You're up-to-date!
Tinkerwell 1.2.0 is currently the newest version available.
```

Downloading now the new version through https://tinkerwell.app Website.

**Comment by sschlein** [comment]
Version 2 is a rewrite from scratch and in a different technology, so we can't update it automatically from 1.2.

We will add an update notification to 1.2 when we have solved all small issues that have a huge impact on support at the moment.

**Comment by spielfigur** [comment]
no problem at all... thanks for the reply.

Schönes Wochenende!
