### ISSUE TITLE
Running AppImage on linux results to wrong Permission of `chrome-sandbox` error

### ISSUE THREAD

**Issue by iraklisg** [beyondcode/tinkerwell-suggestions#83]
I just bought a license for Tinkerwell and I tried to download and run it on Debian 10 (Buster).
However I am getting the following error:
```sh
$ ./Tinkerwell-2.0.1.AppImage

[13180:0129/085800.168523:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary
 was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. 
You need to make sure that /tmp/.mount_TinkerFusqGJ/chrome-sandbox is owned by root and has
 mode 4755.
```

which seems to be related to [this Electron issue](https://github.com/electron/electron/issues/17972#issuecomment-486927073)

I was able to run the application using the `--no-sandbox` flag but when I do this, I cannot run any code (I get the spinning caret but no code is executed)

![Screenshot from 2020-01-29 09-12-13](https://user-images.githubusercontent.com/3668360/73335342-bac16780-4277-11ea-98d8-c79f4bdb5c63.png)

Could you please advice?

**[ UPDATE ]**
Today I was able to successfully run php code using the updated Tinkerwell-**2.1.0**.AppImage along with the `--no-sandbox` flag. 

The reason why I am not closing this issue though is to draw maintainers attention since I still get the `chrome-sandbox` error when running tinkerbell without the `--no-sandbox` flag.

**Comment by mpociot** [comment]
Thank you for bringing this up. I'll look into this - worst case is we document the `--no-sandbox` flag in our FAQ :)
