### ISSUE TITLE
Using With Http Resource

### ISSUE THREAD

**Issue by FutureFutureTo** [beyondcode/tinkerwell-suggestions#84]
Hey there,

I'm having trouble getting the proper output from my resource. It is just returning the model and not custom attributes that I've included in the resource...Any ideas?

```
use App\Http\Resources\User as UserResource;

$user = App\User::find(1);
return new UserResource($user);
```

**Comment by mpociot** [comment]
You probably want to use the `toArray` or `toResponse` methods on your resource object.

![image](https://user-images.githubusercontent.com/804684/74533509-0d667900-4f32-11ea-9455-04e2bf4cb7ce.png)
