### ISSUE TITLE
Unable to select ssh key

### ISSUE THREAD

**Issue by SamuelNitsche** [beyondcode/tinkerwell-suggestions#85]
I have different ssh keys installed on my machine and I am unable to select the correct one. When clicking "Select", I am unable to navigate to the ".ssh" folder on my machine. Hidden files are visible when I open any Finder window.

![Bildschirmfoto 2020-02-02 um 14 27 33](https://user-images.githubusercontent.com/24483576/73608882-69431080-45c8-11ea-83dc-0003a0b2dac2.png)

**Comment by erikverbeek** [comment]
One way I've found to get into hidden folders is to go to the file in the Finder window and drag it into the File Selection window. Then the File Selection window will jump to the folder and select the file you've dragged into it.

**Comment by SamuelNitsche** [comment]
Yep, that worked. Thanks! I think I still keep this issue opened, there should definitely be a better way.

**Comment by erikverbeek** [comment]
I did a bit of googling. The easiest way seems to be using the hotkey Command+Shift+Period. That toggles the hidden files to be shown.

I found an [article](https://nektony.com/how-to/show-hidden-files-on-mac) showing some ways to permanently show hidden files, but they feel a bit hacky.

**Comment by sschlein** [comment]
For the moment, we solve this with a new FAQ:
https://tinkerwell.app/faq/#jump-to-15

Not the best solution long-term but not a priority at the moment.

**Comment by sschlein** [comment]
That actually was a lie. Fixed in the next version 🙈
