### ISSUE TITLE
Documentation does not open

### ISSUE THREAD

**Issue by jeremylemardele** [beyondcode/tinkerwell-suggestions#86]
Hello,

I am trying to open the documentation window (with the Laravel icon), but noting happens in the desktop app. Is there something I should do to make it work?

Moreover, in the web.tinkerwell.app, there are no code, nor any button to add the code to the editor, as shown in this screenshot:

![Capture d’écran 2020-02-02 à 17 22 57](https://user-images.githubusercontent.com/19142403/73616292-e47ce480-4611-11ea-81a3-295b3a1427c3.png)

Thank you for your help!

**Comment by sschlein** [comment]
The Laravel icon of the app does not open the documentation but takes you to the Laravel default app that we ship with Tinkerwell. We'll take care of the docs of the web version soon.
