### ISSUE TITLE
Document how a framework is detected.

### ISSUE THREAD

**Issue by mfullbrook** [beyondcode/tinkerwell-suggestions#89]
It would be helpful if you published how Tinkerwell detects each framework.

I've had to reverse engineer the Tinkerwell phar to learn why my Laravel project wasn't working in Tinkerwell.   

For Laravel it is looking for the existance of two files.  I've changed the directory structure of /public and there is no index.php inside it.  Once I added a dummy file I can now use Tinkerwell but it was a tad frustrating.

```php
class LaravelTinkerwellDriver extends TinkerwellDriver
{
    public function canBootstrap($projectPath)
    {
        return file_exists($projectPath . '/public/index.php') &&
            file_exists($projectPath . '/artisan');
    }
    // ...
```

**Comment by mfullbrook** [comment]
The other suggestion https://github.com/beyondcode/tinkerwell-suggestions/issues/77 of showing an icon for the detected framework would help people with issues similar to me quicker.

**Comment by sschlein** [comment]
Instead of reverse engineering, you could have a look at our blog: https://tinkerwell.app/tutorials/3-how-to-write-a-custom-tinkerwell-driver

And the custom driver repository: https://github.com/tinkerwellapp/drivers

:-)

**Comment by mfullbrook** [comment]
Okay cool, that's helpful.  I didn't know it was a framework detection problem to begin with, I just had this error:

```
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in xxxx/vendor/laravel/framework/src/Illuminate/Container/Container.php:803
```
