### ISSUE TITLE
SSH app folder bug

### ISSUE THREAD

**Issue by filipedtristao** [beyondcode/tinkerwell-suggestions#90]
Regardless of the folder I select in the ssh configuration, the app always goes to home/forge, where I can't work with my site in forge.

The home/forge folder is used even if i type a wrong app directory that does not exist.

![image](https://user-images.githubusercontent.com/10791793/73752653-17bd9180-4740-11ea-9726-328e497bd5df.png)

![image](https://user-images.githubusercontent.com/10791793/73752234-4edf7300-473f-11ea-8956-79e595d3f4f8.png)

**Comment by mpociot** [comment]
This is only regarding the PHP execution. The working dir will be used when running your PHP code.
It's just that the execution itself is happening from outside that directory. But that should not matter.
