### ISSUE TITLE
Possible to debug? Tinkerwell stopped working

### ISSUE THREAD

**Issue by spielfigur** [beyondcode/tinkerwell-suggestions#91]
Hi there,

i have installed the new version 2.1.1 and now tinkerwell stopped working.
the work directory is local, database is mysql on localhost.
if I open tinkerwell and press run, the following information appears:
![Bildschirmfoto 2020-02-05 um 10 01 51](https://user-images.githubusercontent.com/6874264/73827074-32a30b00-47ff-11ea-9840-7fd59c3f1906.png)
when I open 'set working directory' and press open, run again, nothing happens.
![Bildschirmfoto 2020-02-05 um 10 11 14](https://user-images.githubusercontent.com/6874264/73827449-dc829780-47ff-11ea-994e-a3a01d232c80.png)
is it possible to debug what's the problem? 
well I think at the first start the working directory seems to be the default directory?
this would explain the first message.
but what's the problem after I set the working directory?

thanks in advance!

**Comment by sschlein** [comment]
Can you please check if the correct PHP binary is selected in the advanced settings?

**Comment by spielfigur** [comment]
yeah, that did the trick!
i needed to set `/usr/local/bin/php` executable for the 7.4.1 cli.
thank you!
