### ISSUE TITLE
Ability for drivers to define Psy shell aliases

### ISSUE THREAD

**Issue by jasonvarga** [beyondcode/tinkerwell-suggestions#93]
Hi, I recently opened [this PR into laravel/tinker](https://github.com/laravel/tinker/pull/88) that lets you whitelist classes in vendor namespaces.

Would it be possible to allow drivers to define their own set of whitelisted classes/namespaces? Almost like the equivalent of that PR.

For example, when using a Statamic driver, it would be great if all the classes in the `Statamic\Facades` namespace would get automatically aliased.

**Comment by mpociot** [comment]
I think this feature is very specific - as the class aliasing is also only possible with Laravel.
You can, however, take care of this yourself by making use of the [class_alias](https://www.php.net/manual/en/function.class-alias.php) method in your driver and then alias the classes that you want yourself.
