### ISSUE TITLE
Make the Stacktrace Output hideable

### ISSUE THREAD

**Issue by Konafets** [beyondcode/tinkerwell-suggestions#95]
When I run a script inside a TYPO3 environment, I get some PHP Notices. After the StackTrace the desired output is shown. Unfortunately those notices are very common in TYPO3 and normally "hidden" in the console. To show them before the output might scare away some users.

Could you either move the StackTrace output to the very bottom or inside a DevTools-alike console window?

**Comment by sschlein** [comment]
This seems to be related to TYPO3 or the TYPO3 driver and not related to Tinkerwell. Do you think you can fix this within the driver?

**Comment by mpociot** [comment]
@Konafets we can not move the notices around, as they get triggered by the executed code.
Please try disabling notices using `error_reporting(E_ALL & ~E_NOTICE);`
This is usually set within your local php.ini file by default, so you might want to look into that.
If it's common in Typo3 to get notices, maybe this should be done in the driver too.
