### ISSUE TITLE
Tinkerwell does not work when Laravel is not in the main project directory.

### ISSUE THREAD

**Issue by eduardlleshi** [beyondcode/tinkerwell-suggestions#98]
I've got a Docker setup and the application is in the `/src` directory.

When I use the PHPStorm plugin Tinkerwell will throw an error since the `/vendor/autoload.php` cannot be found to do the class mapping.

`Fatal error:  Class 'App/Http/Controllers/Controller' not found in Psy Shell code on line 14`

If I open the Laravel directory through Tinkerwell it will work, and the same would work if I use PHPStorm and open the Laravel directory (which is in `/src`).

Would you mind giving a setting for the plugin to define where the application is in the project we've opened?

**Comment by sschlein** [comment]
That sounds like a huge edge case to me so I think we can't make this a priority anytime soon 😕

Maybe you can make this work by creating a custom driver in the project that bootstraps Laravel from a different folder?

**Comment by eduardlleshi** [comment]
Wasn't aware of Tinkerwell drivers. It sounds doable, but I'm having some issues with it.

I created `CustomTinkerwellDriver.php` inside `.tinkerwell` directory and I can see it loading as I've tested the context menus and dumping stuff.

Tinkerwell app and the PHPStorm plugin are behaving differently, and I can't get either to work.

**PHPStorm plugin:** - looks like it's loading the classes twice(?).
`PHP Fatal error:  Class named App/Http/Controllers/QuoteController already exists in Psy Shell code on line 30`

**Tinkerwell app:** - shows same error even with the custom driver.
`Fatal error: Class 'Quote' not found in Psy Shell code on line 2`

This is the driver (I've added `/src` where needed): https://gist.github.com/eduardlleshi/cd5f1fb1ac66e9ca56832a7c3a6fc0f5

**Comment by mpociot** [comment]
@eduardlleshi  It seems like the "Class 'Quote' not found" issue is because the class aliasing doesn't work for you.
Try using the fully qualified class name instead. I'll look into the PHPStorm plugin issue

**Comment by eduardlleshi** [comment]
@mpociot I created the custom driver so that Tinkerwell can see and do class aliasing even if the application is in a nested folder, which isn't working.

The same custom driver is giving a different error on PHPStorm: `Cannot redeclare xx in Psy Shell code.` which makes me think that it's loading the project files twice.
