### ISSUE TITLE
Connect via SSH never works

### ISSUE THREAD

**Issue by apocalyarts** [beyondcode/tinkerwell-suggestions#99]
I am always getting this error:

![Unbenannt](https://user-images.githubusercontent.com/837443/74545674-9341ee80-4f49-11ea-8d7b-b9d29d2147ea.PNG)

I am on Tinkerwell 2.2.1 (Windows). I added a Forge API Key and tried to connect to one of my Forge Servers. I have no problem reaching my server via SSH using Putty or via SFTP using Filezilla with the exact same private key file.

Or is there anything I am missing?

**Comment by vmitchell85** [comment]
I also cannot get SSH (to forge) working at all...

**Comment by sschlein** [comment]
Can you please check everything that is discussed here? https://github.com/beyondcode/tinkerwell-suggestions/issues/96

There is also mentioned how to check your key. If it doesn't work, please add your question with more detailed information there so that we can follow up in this thread.
